# Generated by Django 5.1.7 on 2025-07-16 04:11

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupApprovalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_limit', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Auto-approve expenses under this amount', max_digits=10)),
                ('receipt_auto_approve_limit', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Auto-approve expenses with receipts under this amount', max_digits=10)),
                ('batch_notifications', models.BooleanField(default=True, help_text='Send daily digest instead of instant notifications')),
                ('notification_time', models.TimeField(default=datetime.time(18, 0, 1, 969424), help_text='Time to send daily digest')),
                ('auto_approve_recurring', models.BooleanField(default=True, help_text='Auto-approve similar recurring expenses')),
                ('require_receipt_above', models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), help_text='Require receipt for expenses above this amount', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMemberTrust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_level', models.CharField(choices=[('new', 'New Member'), ('trusted', 'Trusted Member'), ('co_admin', 'Co-Admin')], default='new', max_length=20)),
                ('total_expenses_created', models.IntegerField(default=0)),
                ('total_expenses_approved', models.IntegerField(default=0)),
                ('rejection_count', models.IntegerField(default=0)),
                ('last_rejection_date', models.DateTimeField(blank=True, null=True)),
                ('auto_approve_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_type',
            field=models.CharField(blank=True, choices=[('auto_amount', 'Auto-approved (Small Amount)'), ('auto_trust', 'Auto-approved (Trusted Member)'), ('auto_receipt', 'Auto-approved (Has Receipt)'), ('manual', 'Manually Approved'), ('batch', 'Batch Approved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='has_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('auto_approved', 'Auto Approved'), ('approved', 'Manually Approved'), ('pending', 'Active - Pending Payment'), ('partial', 'Partially Paid'), ('settled', 'Settled'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'created_at'], name='expense_exp_status_d2a6e6_idx'),
        ),
        migrations.AddField(
            model_name='approvalqueue',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.expense'),
        ),
        migrations.AddField(
            model_name='approvalqueue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupapprovalsettings',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_settings', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupmembertrust',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupmembertrust',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='approvalqueue',
            index=models.Index(fields=['group', '-priority', 'created_at'], name='expense_app_group_i_ae72a7_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembertrust',
            index=models.Index(fields=['group', 'trust_level'], name='expense_gro_group_i_37cc8c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembertrust',
            index=models.Index(fields=['user', 'trust_level'], name='expense_gro_user_id_29ebdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembertrust',
            unique_together={('group', 'user')},
        ),
    ]
