# Generated by Django 5.1.7 on 2025-07-16 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_approvalqueue_groupapprovalsettings_groupmembertrust_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapprovalsettings',
            name='notification_time',
            field=models.TimeField(default=datetime.time(18, 0, 29, 901701), help_text='Time to send daily digest'),
        ),
    ]
